{{- include "tailzero-connector.validateConfig" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tailzero-connector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tailzero-connector.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tailzero-connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tailzero-connector.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "tailzero-connector.generatedServiceAccountName" . }}
      containers:
        - name: tailzero-connector
{{- if .Values.image.override }}
          image: "{{ .Values.image.override }}"
{{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
{{- if .Values.config.inviteCode }}
            - {{ printf "-border0-invite-code=%s" .Values.config.inviteCode | quote }}
{{- end }}
{{- if .Values.config.token }}
            - {{ printf "-border0-token=%s" .Values.config.token | quote }}
{{- end }}
{{- if and .Values.config.inviteCode .Values.config.cache.ssmPath }}
            - {{ printf "-cache-ssm-path=%s" .Values.config.cache.ssmPath | quote }}
{{- else if .Values.config.inviteCode }}
            - {{ printf "-cache-k8s-namespace=%s" (include "tailzero-connector.cacheK8sNamespace" .) | quote }}
            - {{ printf "-cache-k8s-secret-name=%s" (include "tailzero-connector.cacheK8sSecretName" .) | quote }}
{{- end }}
{{- if .Values.config.configDir }}
            - {{ printf "-config-dir=%s" .Values.config.configDir | quote }}
{{- end }}
{{- if .Values.config.hostname }}
            - {{ printf "-hostname=%s" .Values.config.hostname | quote }}
{{- else }}
            - {{ printf "-hostname=%s" .Release.Name | quote }}
{{- end }}
            - {{ printf "-statedir=%s" .Values.config.stateDir | quote }}
{{- if .Values.config.tsAuthKey }}
            - {{ printf "-ts-auth-key=%s" .Values.config.tsAuthKey | quote }}
{{- end }}
{{- if .Values.config.tsControlUrl }}
            - {{ printf "-ts-control-url=%s" .Values.config.tsControlUrl | quote }}
{{- end }}
{{- if .Values.config.tsIdFedClientId }}
            - {{ printf "-ts-id-fed-cid=%s" .Values.config.tsIdFedClientId | quote }}
{{- end }}
{{- if .Values.config.tsIdFedToken }}
            - {{ printf "-ts-id-fed-token=%s" .Values.config.tsIdFedToken | quote }}
{{- end }}
{{- if .Values.config.tsVaultUrl }}
            - {{ printf "-ts-vault-url=%s" .Values.config.tsVaultUrl | quote }}
{{- end }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tailzero-state
              mountPath: {{ .Values.config.stateDir | quote }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: tailzero-state
          emptyDir: {}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
