{{- if and .Values.config.inviteCode (not .Values.config.cache.ssmPath) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tailzero-connector.generatedRoleName" . }}
  namespace: {{ include "tailzero-connector.cacheK8sNamespace" . }}
  labels:
    {{- include "tailzero-connector.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tailzero-connector.generatedServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "tailzero-connector.generatedRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
